# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65ntity.proto\x12\x14toc_python_forwarder\"$\n\x0bStockNumArr\x12\x15\n\rstock_num_arr\x18\x01 \x03(\t\"(\n\rFutureCodeArr\x12\x17\n\x0f\x66uture_code_arr\x18\x01 \x03(\t\"\x1b\n\x0c\x45rrorMessage\x12\x0b\n\x03\x65rr\x18\x01 \x01(\tB\x06Z\x04./pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entity_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _STOCKNUMARR._serialized_start=38
  _STOCKNUMARR._serialized_end=74
  _FUTURECODEARR._serialized_start=76
  _FUTURECODEARR._serialized_end=116
  _ERRORMESSAGE._serialized_start=118
  _ERRORMESSAGE._serialized_end=145
# @@protoc_insertion_point(module_scope)
