"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class BeatMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    message: builtins.str
    error: builtins.str
    def __init__(
        self,
        *,
        message: builtins.str = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "message", b"message"]) -> None: ...

global___BeatMessage = BeatMessage

@typing.final
class ShioajiUsage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONNECTIONS_FIELD_NUMBER: builtins.int
    BYTES_FIELD_NUMBER: builtins.int
    LIMIT_BYTES_FIELD_NUMBER: builtins.int
    REMAINING_BYTES_FIELD_NUMBER: builtins.int
    connections: builtins.int
    bytes: builtins.int
    limit_bytes: builtins.int
    remaining_bytes: builtins.int
    def __init__(
        self,
        *,
        connections: builtins.int = ...,
        bytes: builtins.int = ...,
        limit_bytes: builtins.int = ...,
        remaining_bytes: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bytes", b"bytes", "connections", b"connections", "limit_bytes", b"limit_bytes", "remaining_bytes", b"remaining_bytes"]) -> None: ...

global___ShioajiUsage = ShioajiUsage

@typing.final
class StockDetailResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOCK_FIELD_NUMBER: builtins.int
    @property
    def stock(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StockDetailMessage]: ...
    def __init__(
        self,
        *,
        stock: collections.abc.Iterable[global___StockDetailMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["stock", b"stock"]) -> None: ...

global___StockDetailResponse = StockDetailResponse

@typing.final
class FutureDetailResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FUTURE_FIELD_NUMBER: builtins.int
    @property
    def future(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FutureDetailMessage]: ...
    def __init__(
        self,
        *,
        future: collections.abc.Iterable[global___FutureDetailMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["future", b"future"]) -> None: ...

global___FutureDetailResponse = FutureDetailResponse

@typing.final
class OptionDetailResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPTION_FIELD_NUMBER: builtins.int
    @property
    def option(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___OptionDetailMessage]: ...
    def __init__(
        self,
        *,
        option: collections.abc.Iterable[global___OptionDetailMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["option", b"option"]) -> None: ...

global___OptionDetailResponse = OptionDetailResponse

@typing.final
class StockDetailMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXCHANGE_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    REFERENCE_FIELD_NUMBER: builtins.int
    UPDATE_DATE_FIELD_NUMBER: builtins.int
    DAY_TRADE_FIELD_NUMBER: builtins.int
    exchange: builtins.str
    category: builtins.str
    code: builtins.str
    name: builtins.str
    reference: builtins.float
    update_date: builtins.str
    day_trade: builtins.str
    def __init__(
        self,
        *,
        exchange: builtins.str = ...,
        category: builtins.str = ...,
        code: builtins.str = ...,
        name: builtins.str = ...,
        reference: builtins.float = ...,
        update_date: builtins.str = ...,
        day_trade: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["category", b"category", "code", b"code", "day_trade", b"day_trade", "exchange", b"exchange", "name", b"name", "reference", b"reference", "update_date", b"update_date"]) -> None: ...

global___StockDetailMessage = StockDetailMessage

@typing.final
class FutureDetailMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    DELIVERY_MONTH_FIELD_NUMBER: builtins.int
    DELIVERY_DATE_FIELD_NUMBER: builtins.int
    UNDERLYING_KIND_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    LIMIT_UP_FIELD_NUMBER: builtins.int
    LIMIT_DOWN_FIELD_NUMBER: builtins.int
    REFERENCE_FIELD_NUMBER: builtins.int
    UPDATE_DATE_FIELD_NUMBER: builtins.int
    code: builtins.str
    symbol: builtins.str
    name: builtins.str
    category: builtins.str
    delivery_month: builtins.str
    delivery_date: builtins.str
    underlying_kind: builtins.str
    unit: builtins.int
    limit_up: builtins.float
    limit_down: builtins.float
    reference: builtins.float
    update_date: builtins.str
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        symbol: builtins.str = ...,
        name: builtins.str = ...,
        category: builtins.str = ...,
        delivery_month: builtins.str = ...,
        delivery_date: builtins.str = ...,
        underlying_kind: builtins.str = ...,
        unit: builtins.int = ...,
        limit_up: builtins.float = ...,
        limit_down: builtins.float = ...,
        reference: builtins.float = ...,
        update_date: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["category", b"category", "code", b"code", "delivery_date", b"delivery_date", "delivery_month", b"delivery_month", "limit_down", b"limit_down", "limit_up", b"limit_up", "name", b"name", "reference", b"reference", "symbol", b"symbol", "underlying_kind", b"underlying_kind", "unit", b"unit", "update_date", b"update_date"]) -> None: ...

global___FutureDetailMessage = FutureDetailMessage

@typing.final
class OptionDetailMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    SYMBOL_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    DELIVERY_MONTH_FIELD_NUMBER: builtins.int
    DELIVERY_DATE_FIELD_NUMBER: builtins.int
    STRIKE_PRICE_FIELD_NUMBER: builtins.int
    OPTION_RIGHT_FIELD_NUMBER: builtins.int
    UNDERLYING_KIND_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    LIMIT_UP_FIELD_NUMBER: builtins.int
    LIMIT_DOWN_FIELD_NUMBER: builtins.int
    REFERENCE_FIELD_NUMBER: builtins.int
    UPDATE_DATE_FIELD_NUMBER: builtins.int
    code: builtins.str
    symbol: builtins.str
    name: builtins.str
    category: builtins.str
    delivery_month: builtins.str
    delivery_date: builtins.str
    strike_price: builtins.float
    option_right: builtins.str
    underlying_kind: builtins.str
    unit: builtins.int
    limit_up: builtins.float
    limit_down: builtins.float
    reference: builtins.float
    update_date: builtins.str
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        symbol: builtins.str = ...,
        name: builtins.str = ...,
        category: builtins.str = ...,
        delivery_month: builtins.str = ...,
        delivery_date: builtins.str = ...,
        strike_price: builtins.float = ...,
        option_right: builtins.str = ...,
        underlying_kind: builtins.str = ...,
        unit: builtins.int = ...,
        limit_up: builtins.float = ...,
        limit_down: builtins.float = ...,
        reference: builtins.float = ...,
        update_date: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["category", b"category", "code", b"code", "delivery_date", b"delivery_date", "delivery_month", b"delivery_month", "limit_down", b"limit_down", "limit_up", b"limit_up", "name", b"name", "option_right", b"option_right", "reference", b"reference", "strike_price", b"strike_price", "symbol", b"symbol", "underlying_kind", b"underlying_kind", "unit", b"unit", "update_date", b"update_date"]) -> None: ...

global___OptionDetailMessage = OptionDetailMessage
