"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _WSType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _WSTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WSType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TYPE_FUTURE_TICK: _WSType.ValueType  # 0
    TYPE_FUTURE_ORDER: _WSType.ValueType  # 1
    TYPE_PERIOD_TRADE_VOLUME: _WSType.ValueType  # 2
    TYPE_TRADE_INDEX: _WSType.ValueType  # 3
    TYPE_FUTURE_POSITION: _WSType.ValueType  # 4
    TYPE_ASSIST_STATUS: _WSType.ValueType  # 5
    TYPE_ERR_MESSAGE: _WSType.ValueType  # 6

class WSType(_WSType, metaclass=_WSTypeEnumTypeWrapper): ...

TYPE_FUTURE_TICK: WSType.ValueType  # 0
TYPE_FUTURE_ORDER: WSType.ValueType  # 1
TYPE_PERIOD_TRADE_VOLUME: WSType.ValueType  # 2
TYPE_TRADE_INDEX: WSType.ValueType  # 3
TYPE_FUTURE_POSITION: WSType.ValueType  # 4
TYPE_ASSIST_STATUS: WSType.ValueType  # 5
TYPE_ERR_MESSAGE: WSType.ValueType  # 6
global___WSType = WSType

@typing_extensions.final
class WSMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    FUTURE_TICK_FIELD_NUMBER: builtins.int
    FUTURE_ORDER_FIELD_NUMBER: builtins.int
    PERIOD_TRADE_VOLUME_FIELD_NUMBER: builtins.int
    TRADE_INDEX_FIELD_NUMBER: builtins.int
    FUTURE_POSITION_FIELD_NUMBER: builtins.int
    ASSIT_STATUS_FIELD_NUMBER: builtins.int
    ERR_MESSAGE_FIELD_NUMBER: builtins.int
    type: global___WSType.ValueType
    @property
    def future_tick(self) -> global___WSFutureTick: ...
    @property
    def future_order(self) -> global___WSFutureOrder: ...
    @property
    def period_trade_volume(self) -> global___WSPeriodTradeVolume: ...
    @property
    def trade_index(self) -> global___WSTradeIndex: ...
    @property
    def future_position(self) -> global___WSFuturePosition: ...
    @property
    def assit_status(self) -> global___WSAssitStatus: ...
    @property
    def err_message(self) -> global___WSErrMessage: ...
    def __init__(
        self,
        *,
        type: global___WSType.ValueType = ...,
        future_tick: global___WSFutureTick | None = ...,
        future_order: global___WSFutureOrder | None = ...,
        period_trade_volume: global___WSPeriodTradeVolume | None = ...,
        trade_index: global___WSTradeIndex | None = ...,
        future_position: global___WSFuturePosition | None = ...,
        assit_status: global___WSAssitStatus | None = ...,
        err_message: global___WSErrMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["assit_status", b"assit_status", "data", b"data", "err_message", b"err_message", "future_order", b"future_order", "future_position", b"future_position", "future_tick", b"future_tick", "period_trade_volume", b"period_trade_volume", "trade_index", b"trade_index"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["assit_status", b"assit_status", "data", b"data", "err_message", b"err_message", "future_order", b"future_order", "future_position", b"future_position", "future_tick", b"future_tick", "period_trade_volume", b"period_trade_volume", "trade_index", b"trade_index", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["data", b"data"]) -> typing_extensions.Literal["future_tick", "future_order", "period_trade_volume", "trade_index", "future_position", "assit_status", "err_message"] | None: ...

global___WSMessage = WSMessage

@typing_extensions.final
class WSErrMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERR_CODE_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    err_code: builtins.int
    response: builtins.str
    def __init__(
        self,
        *,
        err_code: builtins.int = ...,
        response: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["err_code", b"err_code", "response", b"response"]) -> None: ...

global___WSErrMessage = WSErrMessage

@typing_extensions.final
class WSFutureOrder(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    BASE_ORDER_FIELD_NUMBER: builtins.int
    code: builtins.str
    @property
    def base_order(self) -> global___WSOrder: ...
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        base_order: global___WSOrder | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["base_order", b"base_order"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["base_order", b"base_order", "code", b"code"]) -> None: ...

global___WSFutureOrder = WSFutureOrder

@typing_extensions.final
class WSOrder(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    ORDER_TIME_FIELD_NUMBER: builtins.int
    ACTION_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    TRADE_TIME_FIELD_NUMBER: builtins.int
    TICK_TIME_FIELD_NUMBER: builtins.int
    GROUP_ID_FIELD_NUMBER: builtins.int
    order_id: builtins.str
    status: builtins.int
    order_time: builtins.str
    action: builtins.int
    price: builtins.float
    quantity: builtins.int
    trade_time: builtins.str
    tick_time: builtins.str
    group_id: builtins.str
    def __init__(
        self,
        *,
        order_id: builtins.str = ...,
        status: builtins.int = ...,
        order_time: builtins.str = ...,
        action: builtins.int = ...,
        price: builtins.float = ...,
        quantity: builtins.int = ...,
        trade_time: builtins.str = ...,
        tick_time: builtins.str = ...,
        group_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["action", b"action", "group_id", b"group_id", "order_id", b"order_id", "order_time", b"order_time", "price", b"price", "quantity", b"quantity", "status", b"status", "tick_time", b"tick_time", "trade_time", b"trade_time"]) -> None: ...

global___WSOrder = WSOrder

@typing_extensions.final
class WSFutureTick(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    TICK_TIME_FIELD_NUMBER: builtins.int
    OPEN_FIELD_NUMBER: builtins.int
    UNDERLYING_PRICE_FIELD_NUMBER: builtins.int
    BID_SIDE_TOTAL_VOL_FIELD_NUMBER: builtins.int
    ASK_SIDE_TOTAL_VOL_FIELD_NUMBER: builtins.int
    AVG_PRICE_FIELD_NUMBER: builtins.int
    CLOSE_FIELD_NUMBER: builtins.int
    HIGH_FIELD_NUMBER: builtins.int
    LOW_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    TOTAL_AMOUNT_FIELD_NUMBER: builtins.int
    VOLUME_FIELD_NUMBER: builtins.int
    TOTAL_VOLUME_FIELD_NUMBER: builtins.int
    TICK_TYPE_FIELD_NUMBER: builtins.int
    CHG_TYPE_FIELD_NUMBER: builtins.int
    PRICE_CHG_FIELD_NUMBER: builtins.int
    PCT_CHG_FIELD_NUMBER: builtins.int
    code: builtins.str
    tick_time: builtins.str
    open: builtins.float
    underlying_price: builtins.float
    bid_side_total_vol: builtins.int
    ask_side_total_vol: builtins.int
    avg_price: builtins.float
    close: builtins.float
    high: builtins.float
    low: builtins.float
    amount: builtins.float
    total_amount: builtins.float
    volume: builtins.int
    total_volume: builtins.int
    tick_type: builtins.int
    chg_type: builtins.int
    price_chg: builtins.float
    pct_chg: builtins.float
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        tick_time: builtins.str = ...,
        open: builtins.float = ...,
        underlying_price: builtins.float = ...,
        bid_side_total_vol: builtins.int = ...,
        ask_side_total_vol: builtins.int = ...,
        avg_price: builtins.float = ...,
        close: builtins.float = ...,
        high: builtins.float = ...,
        low: builtins.float = ...,
        amount: builtins.float = ...,
        total_amount: builtins.float = ...,
        volume: builtins.int = ...,
        total_volume: builtins.int = ...,
        tick_type: builtins.int = ...,
        chg_type: builtins.int = ...,
        price_chg: builtins.float = ...,
        pct_chg: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["amount", b"amount", "ask_side_total_vol", b"ask_side_total_vol", "avg_price", b"avg_price", "bid_side_total_vol", b"bid_side_total_vol", "chg_type", b"chg_type", "close", b"close", "code", b"code", "high", b"high", "low", b"low", "open", b"open", "pct_chg", b"pct_chg", "price_chg", b"price_chg", "tick_time", b"tick_time", "tick_type", b"tick_type", "total_amount", b"total_amount", "total_volume", b"total_volume", "underlying_price", b"underlying_price", "volume", b"volume"]) -> None: ...

global___WSFutureTick = WSFutureTick

@typing_extensions.final
class OutInVolume(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OUT_VOLUME_FIELD_NUMBER: builtins.int
    IN_VOLUME_FIELD_NUMBER: builtins.int
    out_volume: builtins.int
    in_volume: builtins.int
    def __init__(
        self,
        *,
        out_volume: builtins.int = ...,
        in_volume: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["in_volume", b"in_volume", "out_volume", b"out_volume"]) -> None: ...

global___OutInVolume = OutInVolume

@typing_extensions.final
class WSPeriodTradeVolume(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIRST_PERIOD_FIELD_NUMBER: builtins.int
    SECOND_PERIOD_FIELD_NUMBER: builtins.int
    THIRD_PERIOD_FIELD_NUMBER: builtins.int
    FOURTH_PERIOD_FIELD_NUMBER: builtins.int
    @property
    def first_period(self) -> global___OutInVolume: ...
    @property
    def second_period(self) -> global___OutInVolume: ...
    @property
    def third_period(self) -> global___OutInVolume: ...
    @property
    def fourth_period(self) -> global___OutInVolume: ...
    def __init__(
        self,
        *,
        first_period: global___OutInVolume | None = ...,
        second_period: global___OutInVolume | None = ...,
        third_period: global___OutInVolume | None = ...,
        fourth_period: global___OutInVolume | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["first_period", b"first_period", "fourth_period", b"fourth_period", "second_period", b"second_period", "third_period", b"third_period"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["first_period", b"first_period", "fourth_period", b"fourth_period", "second_period", b"second_period", "third_period", b"third_period"]) -> None: ...

global___WSPeriodTradeVolume = WSPeriodTradeVolume

@typing_extensions.final
class WSTradeIndex(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TSE_FIELD_NUMBER: builtins.int
    OTC_FIELD_NUMBER: builtins.int
    NASDAQ_FIELD_NUMBER: builtins.int
    NF_FIELD_NUMBER: builtins.int
    @property
    def tse(self) -> global___WSStockSnapShot: ...
    @property
    def otc(self) -> global___WSStockSnapShot: ...
    @property
    def nasdaq(self) -> global___WSYahooPrice: ...
    @property
    def nf(self) -> global___WSYahooPrice: ...
    def __init__(
        self,
        *,
        tse: global___WSStockSnapShot | None = ...,
        otc: global___WSStockSnapShot | None = ...,
        nasdaq: global___WSYahooPrice | None = ...,
        nf: global___WSYahooPrice | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["nasdaq", b"nasdaq", "nf", b"nf", "otc", b"otc", "tse", b"tse"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["nasdaq", b"nasdaq", "nf", b"nf", "otc", b"otc", "tse", b"tse"]) -> None: ...

global___WSTradeIndex = WSTradeIndex

@typing_extensions.final
class WSStockSnapShot(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STOCK_NUM_FIELD_NUMBER: builtins.int
    STOCK_NAME_FIELD_NUMBER: builtins.int
    SNAP_TIME_FIELD_NUMBER: builtins.int
    OPEN_FIELD_NUMBER: builtins.int
    HIGH_FIELD_NUMBER: builtins.int
    LOW_FIELD_NUMBER: builtins.int
    CLOSE_FIELD_NUMBER: builtins.int
    TICK_TYPE_FIELD_NUMBER: builtins.int
    PRICE_CHG_FIELD_NUMBER: builtins.int
    PCT_CHG_FIELD_NUMBER: builtins.int
    CHG_TYPE_FIELD_NUMBER: builtins.int
    VOLUME_FIELD_NUMBER: builtins.int
    VOLUME_SUM_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    AMOUNT_SUM_FIELD_NUMBER: builtins.int
    YESTERDAY_VOLUME_FIELD_NUMBER: builtins.int
    VOLUME_RATIO_FIELD_NUMBER: builtins.int
    stock_num: builtins.str
    stock_name: builtins.str
    snap_time: builtins.str
    open: builtins.float
    high: builtins.float
    low: builtins.float
    close: builtins.float
    tick_type: builtins.str
    price_chg: builtins.float
    pct_chg: builtins.float
    chg_type: builtins.str
    volume: builtins.int
    volume_sum: builtins.int
    amount: builtins.int
    amount_sum: builtins.int
    yesterday_volume: builtins.float
    volume_ratio: builtins.float
    def __init__(
        self,
        *,
        stock_num: builtins.str = ...,
        stock_name: builtins.str = ...,
        snap_time: builtins.str = ...,
        open: builtins.float = ...,
        high: builtins.float = ...,
        low: builtins.float = ...,
        close: builtins.float = ...,
        tick_type: builtins.str = ...,
        price_chg: builtins.float = ...,
        pct_chg: builtins.float = ...,
        chg_type: builtins.str = ...,
        volume: builtins.int = ...,
        volume_sum: builtins.int = ...,
        amount: builtins.int = ...,
        amount_sum: builtins.int = ...,
        yesterday_volume: builtins.float = ...,
        volume_ratio: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["amount", b"amount", "amount_sum", b"amount_sum", "chg_type", b"chg_type", "close", b"close", "high", b"high", "low", b"low", "open", b"open", "pct_chg", b"pct_chg", "price_chg", b"price_chg", "snap_time", b"snap_time", "stock_name", b"stock_name", "stock_num", b"stock_num", "tick_type", b"tick_type", "volume", b"volume", "volume_ratio", b"volume_ratio", "volume_sum", b"volume_sum", "yesterday_volume", b"yesterday_volume"]) -> None: ...

global___WSStockSnapShot = WSStockSnapShot

@typing_extensions.final
class WSYahooPrice(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LAST_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    last: builtins.float
    price: builtins.float
    updated_at: builtins.str
    def __init__(
        self,
        *,
        last: builtins.float = ...,
        price: builtins.float = ...,
        updated_at: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["last", b"last", "price", b"price", "updated_at", b"updated_at"]) -> None: ...

global___WSYahooPrice = WSYahooPrice

@typing_extensions.final
class WSFuturePosition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POSITION_FIELD_NUMBER: builtins.int
    @property
    def position(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Position]: ...
    def __init__(
        self,
        *,
        position: collections.abc.Iterable[global___Position] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["position", b"position"]) -> None: ...

global___WSFuturePosition = WSFuturePosition

@typing_extensions.final
class Position(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    LAST_PRICE_FIELD_NUMBER: builtins.int
    PNL_FIELD_NUMBER: builtins.int
    code: builtins.str
    direction: builtins.str
    quantity: builtins.int
    price: builtins.float
    last_price: builtins.float
    pnl: builtins.float
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        direction: builtins.str = ...,
        quantity: builtins.int = ...,
        price: builtins.float = ...,
        last_price: builtins.float = ...,
        pnl: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code", b"code", "direction", b"direction", "last_price", b"last_price", "pnl", b"pnl", "price", b"price", "quantity", b"quantity"]) -> None: ...

global___Position = Position

@typing_extensions.final
class WSAssitStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUNNING_FIELD_NUMBER: builtins.int
    running: builtins.bool
    def __init__(
        self,
        *,
        running: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["running", b"running"]) -> None: ...

global___WSAssitStatus = WSAssitStatus
