"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class HistoryTickResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HistoryTickMessage]: ...
    def __init__(
        self,
        *,
        data: collections.abc.Iterable[global___HistoryTickMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data"]) -> None: ...

global___HistoryTickResponse = HistoryTickResponse

class HistoryTickMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TS_FIELD_NUMBER: builtins.int
    CLOSE_FIELD_NUMBER: builtins.int
    VOLUME_FIELD_NUMBER: builtins.int
    BID_PRICE_FIELD_NUMBER: builtins.int
    BID_VOLUME_FIELD_NUMBER: builtins.int
    ASK_PRICE_FIELD_NUMBER: builtins.int
    ASK_VOLUME_FIELD_NUMBER: builtins.int
    TICK_TYPE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    ts: builtins.int
    close: builtins.float
    volume: builtins.int
    bid_price: builtins.float
    bid_volume: builtins.int
    ask_price: builtins.float
    ask_volume: builtins.int
    tick_type: builtins.int
    code: builtins.str
    def __init__(
        self,
        *,
        ts: builtins.int = ...,
        close: builtins.float = ...,
        volume: builtins.int = ...,
        bid_price: builtins.float = ...,
        bid_volume: builtins.int = ...,
        ask_price: builtins.float = ...,
        ask_volume: builtins.int = ...,
        tick_type: builtins.int = ...,
        code: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ask_price", b"ask_price", "ask_volume", b"ask_volume", "bid_price", b"bid_price", "bid_volume", b"bid_volume", "close", b"close", "code", b"code", "tick_type", b"tick_type", "ts", b"ts", "volume", b"volume"]) -> None: ...

global___HistoryTickMessage = HistoryTickMessage

class HistoryKbarResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HistoryKbarMessage]: ...
    def __init__(
        self,
        *,
        data: collections.abc.Iterable[global___HistoryKbarMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data"]) -> None: ...

global___HistoryKbarResponse = HistoryKbarResponse

class HistoryKbarMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TS_FIELD_NUMBER: builtins.int
    CLOSE_FIELD_NUMBER: builtins.int
    OPEN_FIELD_NUMBER: builtins.int
    HIGH_FIELD_NUMBER: builtins.int
    LOW_FIELD_NUMBER: builtins.int
    VOLUME_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    ts: builtins.int
    close: builtins.float
    open: builtins.float
    high: builtins.float
    low: builtins.float
    volume: builtins.int
    code: builtins.str
    def __init__(
        self,
        *,
        ts: builtins.int = ...,
        close: builtins.float = ...,
        open: builtins.float = ...,
        high: builtins.float = ...,
        low: builtins.float = ...,
        volume: builtins.int = ...,
        code: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["close", b"close", "code", b"code", "high", b"high", "low", b"low", "open", b"open", "ts", b"ts", "volume", b"volume"]) -> None: ...

global___HistoryKbarMessage = HistoryKbarMessage

class HistoryCloseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HistoryCloseMessage]: ...
    def __init__(
        self,
        *,
        data: collections.abc.Iterable[global___HistoryCloseMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data"]) -> None: ...

global___HistoryCloseResponse = HistoryCloseResponse

class HistoryCloseMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    CLOSE_FIELD_NUMBER: builtins.int
    date: builtins.str
    code: builtins.str
    close: builtins.float
    def __init__(
        self,
        *,
        date: builtins.str = ...,
        code: builtins.str = ...,
        close: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["close", b"close", "code", b"code", "date", b"date"]) -> None: ...

global___HistoryCloseMessage = HistoryCloseMessage
