# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrade.proto\x12\nhelloworld\"\x17\n\x04\x45\x63ho\x12\x0f\n\x07message\x18\x01 \x01(\t2H\n\x11ToCSinopacBackEnd\x12\x33\n\x0bHealthCheck\x12\x10.helloworld.Echo\x1a\x10.helloworld.Echo\"\x00\x62\x06proto3')



_ECHO = DESCRIPTOR.message_types_by_name['Echo']
Echo = _reflection.GeneratedProtocolMessageType('Echo', (_message.Message,), {
  'DESCRIPTOR' : _ECHO,
  '__module__' : 'trade_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Echo)
  })
_sym_db.RegisterMessage(Echo)

_TOCSINOPACBACKEND = DESCRIPTOR.services_by_name['ToCSinopacBackEnd']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ECHO._serialized_start=27
  _ECHO._serialized_end=50
  _TOCSINOPACBACKEND._serialized_start=52
  _TOCSINOPACBACKEND._serialized_end=124
# @@protoc_insertion_point(module_scope)
